//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization.Main
{
    public static class MainView
    {
        public static readonly string Title = nameof(Title);
        public static readonly string Exit = nameof(Exit);
    }
}
namespace Localization.Main
{
    public static class SettingView
    {
        public static readonly string Title = nameof(Title);
        public static readonly string NoPrompt = nameof(NoPrompt);
    }
}
namespace Localization.DevelopModule
{
    public static class Title2SlugView
    {
        public static readonly string Title = nameof(Title);
        public static readonly string Convert = nameof(Convert);
    }
}
namespace Localization.DevelopModule
{
    public static class SettingView
    {
        public static readonly string Title = nameof(Title);
        public static readonly string MaxLength = nameof(MaxLength);
    }
}
