
//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------

namespace AvaloniaExtensions.Axaml.Demo.I18n;

public static class Language
{
	public static readonly string AppName = "AppName";
	public static readonly string Welcome = "Welcome";
	public static readonly string Running = "Running";
	public static readonly string NotRunning = "NotRunning";
	public static readonly string RunningCountInfo = "RunningCountInfo";
	public static readonly string CurrentTimeFormat = "CurrentTimeFormat";
}
